<a href="https://colab.research.google.com/github/Ysabellyysa/Python/blob/main/Classifica%C3%A7%C3%A3o_Bin%C3%A1ria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Brest Cancer simples

In [1]:
import pandas as pd

In [2]:
#previsores
X = pd.read_csv('/content/entradas_breast.csv')
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.12380,0.18660,0.2416,186.0000,275.0000,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.14440,0.42450,0.4504,243.0000,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,173.00000
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,198.00000,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.13740,205.00000,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,111.00000,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.45,26.40,166.10,2027.0,141.00000,0.21130,0.4107,0.2216,206.0000,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,144.00000,0.09791,0.1752,0.05533,...,23.69,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,159.0000,0.05648,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,277.00000,0.35140,152.00000,0.2397,0.07016,...,25.74,39.42,184.60,1821.0,165.00000,0.86810,0.9387,265.0000,0.4087,124.00000
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9456.00,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [3]:
# class
y = pd.read_csv('/content/saidas_breast.csv')
y

     0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [4]:
import sklearn
from sklearn.model_selection import train_test_split

In [5]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.25)

In [6]:
X_treinamento.shape, y_treinamento.shape

((426, 30), (426, 1))

In [7]:
X_teste.shape, y_teste.shape

((143, 30), (143, 1))

In [8]:
#Criação da estrutura da Rede Neural
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [9]:
(30 + 1) / 2

15.5

In [28]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    tf.keras.layers.Dense(units = 16, activation= 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 16, activation= 'relu', kernel_initializer= 'random_uniform'),
    tf.keras.layers.Dense(units = 1, activation= 'sigmoid')
])

In [11]:
30 * 16, 496 - 480, 30 * 16 + 16 #Bias

(480, 16, 496)

In [12]:
496 + 17

513

In [29]:
rede_neural.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
426 / 10

42.6

In [30]:
otimizador = tf.keras.optimizers.Adam(learning_rate= 0.001, clipvalue = 0.5)

In [31]:
rede_neural.compile(optimizer = otimizador , loss = 'binary_crossentropy', metrics = ['binary_accuracy'])

In [32]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.6479 - loss: 0.9073
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7347 - loss: 0.4977
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7793 - loss: 0.4709
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7817 - loss: 0.4680
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7981 - loss: 0.4385
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8404 - loss: 0.3950
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8028 - loss: 0.4696
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8592 - loss: 0.3735
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8521 - loss: 0.3710
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8474 - loss: 0.5041
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8498 - loss: 0.4126
Epoch 12/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8498 - loss: 0.4138
Epoch 13/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8568 - loss: 0.4462
Epoch 14/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8263 - loss: 0.4921
Epoch 15/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8638 - loss: 0.4387
Epoch 16/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8662 - loss: 0.4520
Epoch 17/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8146 - loss: 0.6396
Epoch 18/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8592 - loss: 0.3857
Epoch 19/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8122 - loss: 0.6273
Epoch 20/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8498 - loss: 0.5184
Epoch 21/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8404 - loss: 0.4521
Epoch 22/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8662 - loss: 0.4771
Epoch 23/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8286 - loss: 0.4791
Epoch 24/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.4701
Epoch 25/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8662 - loss: 0.4650
Epoch 26/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8732 - loss: 0.4455
Epoch 27/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8873 - loss: 0.3570
Epoch 28/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8592 - loss: 0.4111
Epoch 29/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8498 - loss: 0.5721
Epoch 30/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8638 - loss: 0.4675
Epoch 31/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8638 - loss: 0.3615
Epoch 32/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8944 - loss: 0.2954
Epoch 33/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 0.4543
Epoch 34/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8897 - loss: 0.4687
Epoch 35/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8756 - loss: 0.4113
Epoch 36/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8592 - loss: 0.4191
Epoch 37/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8756 - loss: 0.4212
Epoch 38/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8685 - loss: 0.5636
Epoch 39/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8850 - loss: 0.5590
Epoch 40/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8850 - loss: 0.4729
Epoch 41/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8192 - loss: 0.5694
Epoch 42/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8333 - loss: 0.4891
Epoch 43/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8732 - loss: 0.4474
Epoch 44/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8709 - loss: 0.4539
Epoch 45/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8404 - loss: 0.5115
Epoch 46/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8615 - loss: 0.4553
Epoch 47/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8568 - loss: 0.4180
Epoch 48/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8873 - loss: 0.4406
Epoch 49/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8545 - loss: 0.5313
Epoch 50/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8545 - loss: 0.5957
Epoch 51/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8380 - loss: 0.5461
Epoch 52/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8638 - loss: 0.4620
Epoch 53/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8756 - loss: 0.3851
Epoch 54/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8122 - loss: 0.7058
Epoch 55/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8263 - loss: 0.7614
Epoch 56/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8685 - loss: 0.4394
Epoch 57/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9085 - loss: 0.3453
Epoch 58/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8545 - loss: 0.4254
Epoch 59/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8803 - loss: 0.4895
Epoch 60/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8967 - loss: 0.4748
Epoch 61/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8944 - loss: 0.5179
Epoch 62/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8709 - loss: 0.5609
Epoch 63/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8803 - loss: 0.5631
Epoch 64/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8146 - loss: 1.0069
Epoch 65/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8826 - loss: 0.4790
Epoch 66/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8216 - loss: 0.7070
Epoch 67/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8427 - loss: 0.9569
Epoch 68/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8122 - loss: 0.7343
Epoch 69/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8568 - loss: 0.5736
Epoch 70/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7911 - loss: 0.8757
Epoch 71/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8662 - loss: 0.5998
Epoch 72/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8239 - loss: 1.1611
Epoch 73/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8286 - loss: 1.0191
Epoch 74/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8075 - loss: 1.1638
Epoch 75/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8709 - loss: 0.4514
Epoch 76/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8592 - loss: 0.4593
Epoch 77/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8662 - loss: 0.6355
Epoch 78/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8685 - loss: 0.6197
Epoch 79/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8685 - loss: 0.6138
Epoch 80/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8099 - loss: 0.9360
Epoch 81/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.7096
Epoch 82/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8404 - loss: 0.8728
Epoch 83/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8474 - loss: 0.7608
Epoch 84/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8685 - loss: 0.5321
Epoch 85/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8592 - loss: 0.8563
Epoch 86/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8216 - loss: 1.0697
Epoch 87/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8756 - loss: 0.8786
Epoch 88/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8192 - loss: 1.2615
Epoch 89/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7723 - loss: 2.3386
Epoch 90/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8075 - loss: 1.1164
Epoch 91/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8310 - loss: 1.0449
Epoch 92/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8239 - loss: 0.9631
Epoch 93/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8286 - loss: 1.9485
Epoch 94/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8404 - loss: 1.0199
Epoch 95/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8216 - loss: 0.7817
Epoch 96/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8333 - loss: 0.7309
Epoch 97/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8498 - loss: 0.7123
Epoch 98/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8545 - loss: 0.5868
Epoch 99/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8310 - loss: 0.7317
Epoch 100/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8474 - loss: 0.7900

In [35]:
pesos0 = rede_neural.layers[0].get_weights()
pesos0

[array([[-8.41040835e-02, -4.13305372e-01,  1.67748019e-01,
          3.21203113e-01, -2.57564247e-01, -3.54633555e-02,
         -9.74800810e-03,  4.55097184e-02, -1.87658370e-01,
         -2.06449687e-01, -6.46032160e-03,  9.36300233e-02,
          2.72975653e-01, -6.08078064e-03, -2.27423370e-01,
         -1.89542964e-01],
        [-1.19940519e-01, -3.84373069e-01,  1.03073783e-01,
          8.61470774e-02, -2.19424441e-01,  4.06998694e-02,
         -9.83520504e-03,  6.06499761e-02, -2.73123711e-01,
         -2.61363536e-01, -6.44813776e-02,  9.30295214e-02,
          1.39345616e-01, -1.10147908e-01, -2.57071674e-01,
         -1.30309582e-01],
        [-2.96124164e-02, -1.38775274e-01, -2.88606640e-02,
          1.27131656e-01, -8.37205350e-02,  1.56258214e-02,
          1.32942395e-02,  4.25583823e-03,  1.01110414e-02,
          2.44264174e-02,  1.61488615e-02, -3.75520810e-02,
         -6.29283546e-04, -5.21798953e-02, -8.94914120e-02,
         -1.11548081e-01],
        [ 6.23001531e-02,  8.93363357e-02,  8.32318217e-02,
         -1.33055476e-02,  3.79954241e-02,  5.25312871e-02,
         -6.54349774e-02,  1.32961888e-02,  4.23180498e-02,
          1.11098904e-02, -1.28976051e-02, -5.05221039e-02,
          3.77732702e-02, -6.78455085e-02,  3.17134075e-02,
          3.65321077e-02],
        [-2.17338130e-01, -6.74763247e-02, -6.21553361e-02,
         -5.60642453e-03,  3.58517282e-02,  9.09164548e-04,
          1.13343662e-02,  3.46812271e-02, -1.00265563e-01,
         -7.15642571e-02,  8.00602362e-02,  1.14694320e-01,
          4.10203123e-03,  8.54450092e-02, -1.50322229e-01,
          2.79432964e-02],
        [ 8.64460021e-02, -4.76313382e-02, -4.27916646e-02,
         -3.46788019e-03, -2.33719032e-02,  6.21417090e-02,
         -3.36464904e-02, -1.33192077e-01,  1.34290114e-01,
          5.43462858e-02,  7.20415264e-03,  7.85897225e-02,
         -8.21702853e-02,  2.15107188e-01,  1.28987730e-02,
         -1.30113676e-01],
        [-6.30674958e-02, -4.63839024e-02, -8.14283043e-02,
         -4.83636446e-02, -4.02038582e-02,  4.46232855e-02,
         -6.12964407e-02, -6.27183393e-02, -1.32574409e-01,
         -1.55914165e-02, -2.57992838e-03,  1.53642088e-01,
         -5.83635904e-02,  3.03297915e-04, -6.01497246e-03,
         -6.36466919e-03],
        [-1.94695100e-01, -2.00386852e-01,  1.16951562e-01,
         -5.25454350e-04, -1.72490731e-01, -9.38213393e-02,
         -2.92392652e-02, -6.22700416e-02,  2.04338267e-01,
         -1.03330411e-01,  1.71460304e-02, -8.02087262e-02,
          4.83364594e-04,  4.53509152e-01,  2.88575515e-02,
         -7.07322508e-02],
        [-6.13481924e-02, -3.82297933e-02, -2.37579867e-01,
          2.89430935e-02, -6.12973347e-02, -2.80972600e-01,
          1.02164857e-02, -7.41614848e-02, -1.46712959e-02,
          9.71799642e-02,  1.81576870e-02, -1.05980761e-01,
         -1.38011113e-01, -4.29106392e-02, -1.21372808e-02,
          3.05580776e-02],
        [ 2.40151823e-01,  3.39201987e-01,  1.83497623e-01,
          1.50116116e-01,  1.48887619e-01,  1.65658027e-01,
         -4.95038256e-02,  1.40053984e-02, -4.05302122e-02,
         -5.75632639e-02,  2.88622230e-02,  2.08498035e-02,
          2.09859200e-02, -2.39923656e-01,  1.13911219e-01,
          2.03647166e-01],
        [ 4.80304807e-02, -1.55230656e-01,  2.06261594e-02,
         -2.33767014e-02,  2.36785915e-02,  7.74614047e-03,
         -7.91033283e-02, -6.56653196e-02,  6.13264069e-02,
         -1.21047638e-01,  4.29566251e-03, -2.91749276e-02,
         -1.31248934e-02,  7.12083327e-03, -3.22773084e-02,
         -2.47842427e-02],
        [ 5.33956662e-02, -1.32191449e-01, -4.01819544e-03,
          8.08310285e-02, -2.85984427e-02, -5.67348395e-03,
          2.28766631e-02, -5.29821701e-02,  2.16819108e-01,
          1.39614427e-02,  6.49129506e-03, -1.35157872e-02,
         -4.57793400e-02,  1.50923893e-01,  1.49486989e-01,
         -2.87027117e-02],
        [-4.32772823e-02,  8.51373225e-02,  4.75926176e-02,
          1.40565550e-02,  1.26240943e-02,  5.75950406e-02,
         -2.59403400e-02,  2.35596988e-02,  3.66006754e-02,
          1.46667082e-02, -1.28894858e-02, -1.18550397e-02,
          6.84327260e-02,  7.01480210e-02, -4.00695158e-03,
          3.48143652e-02],
        [ 3.47671956e-02, -9.51403022e-01,  3.08992416e-01,
          2.52848387e-01, -1.84271708e-01,  3.63248587e-01,
         -4.48117070e-02,  2.98846722e-01, -3.70421022e-01,
         -7.62148380e-01, -5.96687291e-03,  3.83004457e-01,
          6.94596529e-01, -3.41757029e-01, -6.80524230e-01,
          1.10731579e-01],
        [-1.13979340e-01, -2.38241628e-01,  9.28341970e-02,
          1.39620110e-01, -1.79059088e-01,  1.16987109e-01,
          6.41153369e-04,  1.25571847e-01, -3.45447361e-01,
         -1.53247729e-01, -3.73975635e-02,  2.51272976e-01,
          5.32709025e-02, -2.73471922e-01, -2.73474216e-01,
         -1.26180917e-01],
        [-1.14462063e-01, -2.47986183e-01,  5.19472398e-02,
         -1.61655061e-02, -5.22358268e-02,  1.05869070e-01,
          5.47224320e-02,  3.65207233e-02, -1.53931484e-01,
         -1.64267048e-02,  5.09677120e-02, -7.84308016e-02,
          2.82941163e-01,  7.65068531e-02, -3.15730423e-01,
         -1.01133801e-01],
        [-5.38370907e-02, -9.14357156e-02, -5.58921136e-02,
         -7.36455172e-02, -5.86270913e-02, -1.19184017e-01,
         -2.22186875e-02, -1.88279837e-01,  2.85208076e-01,
          1.17755644e-01,  2.85326634e-02, -2.52908021e-01,
         -5.04844598e-02,  3.86847496e-01,  2.82812625e-01,
         -3.35963786e-01],
        [ 4.47880745e-01, -9.78966281e-02, -1.55243754e-01,
          7.11560845e-02, -6.18057922e-02, -3.13493758e-02,
         -1.69793796e-02, -1.92908034e-01,  4.86551732e-01,
          1.74678445e-01, -4.37568277e-02, -1.36614010e-01,
          2.66107414e-02,  3.37497026e-01,  2.56740928e-01,
         -1.76853836e-01],
        [ 7.19717704e-03,  4.53553945e-01, -1.73095733e-01,
         -9.42994282e-02, -8.31906032e-03,  3.73371039e-03,
         -6.38114959e-02, -1.19334109e-01,  5.97011708e-02,
          2.41643503e-01, -3.75949852e-02, -1.39436662e-01,
         -3.38276476e-01, -3.57796609e-01,  1.59819290e-01,
          1.09070681e-01],
        [-2.24129543e-01, -2.26395190e-01,  3.84776443e-01,
         -1.91149846e-01,  7.69059807e-02,  1.60006464e-01,
         -1.98481828e-02,  2.67062336e-01, -4.34279472e-01,
         -3.09531659e-01,  7.09814066e-03,  5.71585059e-01,
          3.13584149e-01, -3.72460634e-01, -4.10116136e-01,
          2.15786383e-01],
        [-1.01954877e-01, -4.99551773e-01,  1.40050098e-01,
          3.27302784e-01, -2.42462024e-01,  4.62773666e-02,
         -3.50542404e-02,  8.69732797e-02, -2.65027285e-01,
         -2.92777270e-01, -5.27573526e-02,  1.30017161e-01,
          2.38734677e-01,  4.97126020e-02, -1.77578360e-01,
         -2.03939795e-01],
        [-1.21154450e-01, -4.28973913e-01,  2.12438494e-01,
          1.39706150e-01, -1.68709800e-01,  4.49250937e-02,
         -8.09983991e-04,  1.20263740e-01, -3.48688781e-01,
         -3.25309604e-01, -5.91744483e-02,  6.98499382e-02,
          2.06707567e-01, -1.97124898e-01, -3.14756811e-01,
         -1.64890781e-01],
        [ 1.36782341e-02, -1.79883644e-01,  2.28997767e-02,
          6.43424019e-02, -5.04973866e-02,  2.46488173e-02,
          1.42910164e-02, -2.85635944e-02, -7.44352415e-02,
         -1.40644079e-02,  1.84566807e-02, -7.82130286e-02,
          5.92956357e-02, -9.44913030e-02, -1.86719105e-01,
         -2.57942844e-02],
        [ 1.01177588e-01,  4.99767661e-02,  1.22627974e-01,
          4.44451384e-02,  9.89382565e-02,  1.92785505e-02,
         -5.99090159e-02,  8.90511498e-02,  3.77936177e-02,
         -1.01029962e-01, -3.42117324e-02,  8.09109807e-02,
          1.04668908e-01, -7.31693506e-02, -1.75771378e-02,
          4.52216575e-03],
        [-1.99194506e-01, -1.50351331e-01, -2.90478151e-02,
         -8.36983845e-02, -4.41482812e-02,  3.38701643e-02,
         -1.27493711e-02, -2.83830613e-02, -1.12377487e-01,
         -8.97077024e-02,  4.84277029e-03, -4.71413769e-02,
         -4.56028525e-03,  4.88145836e-02, -9.00269896e-02,
         -8.02772790e-02],
        [-8.99817124e-02, -1.64091334e-01, -8.00468214e-03,
         -1.26235232e-01, -6.29020333e-02, -6.72698542e-02,
         -5.04876263e-02, -3.49023044e-02,  2.20111124e-02,
          1.20459404e-02, -3.07002142e-02, -2.75261216e-02,
         -5.60710058e-02,  5.13369106e-02, -8.32454041e-02,
          9.23626572e-02],
        [ 1.72568914e-02, -1.02937058e-01, -2.20883518e-01,
         -1.13318130e-01, -5.81419580e-02, -6.19196743e-02,
         -2.43756231e-02, -6.50150031e-02, -2.50460412e-02,
          1.49124429e-01,  4.32011485e-02, -5.17427437e-02,
         -5.98195866e-02,  7.71416202e-02, -3.08205876e-02,
         -5.04946597e-02],
        [-1.30655006e-01, -3.74162197e-01,  4.57914397e-02,
         -4.21384536e-02,  3.28000821e-02, -1.77370086e-01,
         -5.09043671e-02,  3.48788104e-03,  2.06616707e-02,
         -1.55132607e-01,  2.35120114e-02,  4.17811684e-02,
          1.52736604e-01, -4.13659848e-02, -1.00097187e-01,
          7.20804604e-03],
        [ 6.21403009e-02, -1.46256581e-01, -6.29504323e-02,
         -1.52101070e-01, -5.36352918e-02, -2.80308072e-02,
         -2.91346740e-02, -5.48543073e-02, -2.68510971e-02,
         -6.54924614e-03, -5.65094687e-02, -8.77962634e-03,
         -3.88033651e-02,  1.51318852e-02, -1.13780349e-01,
          2.04025321e-02],
        [-1.56409308e-01, -1.19627044e-01, -5.14307478e-03,
         -1.26988739e-01,  2.33218640e-01, -1.17881201e-01,
         -5.39907664e-02,  1.21948667e-01, -1.87665582e-01,
         -2.62252361e-01, -3.02973352e-02,  4.32836890e-01,
          2.14985553e-02, -1.99544981e-01, -2.22640753e-01,
          2.05753177e-01]], dtype=float32),
 array([ 0.12756959,  0.01842907, -0.1711058 ,  0.2809315 , -0.17765915,
         0.18207215, -0.02667869, -0.20263208,  0.10507656,  0.1503791 ,
        -0.051494  , -0.19332401, -0.20732865, -0.00784816,  0.05680246,
        -0.2974647 ], dtype=float32)]

In [36]:
len(pesos0)

2

In [37]:
len(pesos0[1])

16

In [38]:
pesos0[0]

array([[-8.41040835e-02, -4.13305372e-01,  1.67748019e-01,
         3.21203113e-01, -2.57564247e-01, -3.54633555e-02,
        -9.74800810e-03,  4.55097184e-02, -1.87658370e-01,
        -2.06449687e-01, -6.46032160e-03,  9.36300233e-02,
         2.72975653e-01, -6.08078064e-03, -2.27423370e-01,
        -1.89542964e-01],
       [-1.19940519e-01, -3.84373069e-01,  1.03073783e-01,
         8.61470774e-02, -2.19424441e-01,  4.06998694e-02,
        -9.83520504e-03,  6.06499761e-02, -2.73123711e-01,
        -2.61363536e-01, -6.44813776e-02,  9.30295214e-02,
         1.39345616e-01, -1.10147908e-01, -2.57071674e-01,
        -1.30309582e-01],
       [-2.96124164e-02, -1.38775274e-01, -2.88606640e-02,
         1.27131656e-01, -8.37205350e-02,  1.56258214e-02,
         1.32942395e-02,  4.25583823e-03,  1.01110414e-02,
         2.44264174e-02,  1.61488615e-02, -3.75520810e-02,
        -6.29283546e-04, -5.21798953e-02, -8.94914120e-02,
        -1.11548081e-01],
       [ 6.23001531e-02,  8.93363357e-02,  8.32318217e-02,
        -1.33055476e-02,  3.79954241e-02,  5.25312871e-02,
        -6.54349774e-02,  1.32961888e-02,  4.23180498e-02,
         1.11098904e-02, -1.28976051e-02, -5.05221039e-02,
         3.77732702e-02, -6.78455085e-02,  3.17134075e-02,
         3.65321077e-02],
       [-2.17338130e-01, -6.74763247e-02, -6.21553361e-02,
        -5.60642453e-03,  3.58517282e-02,  9.09164548e-04,
         1.13343662e-02,  3.46812271e-02, -1.00265563e-01,
        -7.15642571e-02,  8.00602362e-02,  1.14694320e-01,
         4.10203123e-03,  8.54450092e-02, -1.50322229e-01,
         2.79432964e-02],
       [ 8.64460021e-02, -4.76313382e-02, -4.27916646e-02,
        -3.46788019e-03, -2.33719032e-02,  6.21417090e-02,
        -3.36464904e-02, -1.33192077e-01,  1.34290114e-01,
         5.43462858e-02,  7.20415264e-03,  7.85897225e-02,
        -8.21702853e-02,  2.15107188e-01,  1.28987730e-02,
        -1.30113676e-01],
       [-6.30674958e-02, -4.63839024e-02, -8.14283043e-02,
        -4.83636446e-02, -4.02038582e-02,  4.46232855e-02,
        -6.12964407e-02, -6.27183393e-02, -1.32574409e-01,
        -1.55914165e-02, -2.57992838e-03,  1.53642088e-01,
        -5.83635904e-02,  3.03297915e-04, -6.01497246e-03,
        -6.36466919e-03],
       [-1.94695100e-01, -2.00386852e-01,  1.16951562e-01,
        -5.25454350e-04, -1.72490731e-01, -9.38213393e-02,
        -2.92392652e-02, -6.22700416e-02,  2.04338267e-01,
        -1.03330411e-01,  1.71460304e-02, -8.02087262e-02,
         4.83364594e-04,  4.53509152e-01,  2.88575515e-02,
        -7.07322508e-02],
       [-6.13481924e-02, -3.82297933e-02, -2.37579867e-01,
         2.89430935e-02, -6.12973347e-02, -2.80972600e-01,
         1.02164857e-02, -7.41614848e-02, -1.46712959e-02,
         9.71799642e-02,  1.81576870e-02, -1.05980761e-01,
        -1.38011113e-01, -4.29106392e-02, -1.21372808e-02,
         3.05580776e-02],
       [ 2.40151823e-01,  3.39201987e-01,  1.83497623e-01,
         1.50116116e-01,  1.48887619e-01,  1.65658027e-01,
        -4.95038256e-02,  1.40053984e-02, -4.05302122e-02,
        -5.75632639e-02,  2.88622230e-02,  2.08498035e-02,
         2.09859200e-02, -2.39923656e-01,  1.13911219e-01,
         2.03647166e-01],
       [ 4.80304807e-02, -1.55230656e-01,  2.06261594e-02,
        -2.33767014e-02,  2.36785915e-02,  7.74614047e-03,
        -7.91033283e-02, -6.56653196e-02,  6.13264069e-02,
        -1.21047638e-01,  4.29566251e-03, -2.91749276e-02,
        -1.31248934e-02,  7.12083327e-03, -3.22773084e-02,
        -2.47842427e-02],
       [ 5.33956662e-02, -1.32191449e-01, -4.01819544e-03,
         8.08310285e-02, -2.85984427e-02, -5.67348395e-03,
         2.28766631e-02, -5.29821701e-02,  2.16819108e-01,
         1.39614427e-02,  6.49129506e-03, -1.35157872e-02,
        -4.57793400e-02,  1.50923893e-01,  1.49486989e-01,
        -2.87027117e-02],
       [-4.32772823e-02,  8.51373225e-02,  4.75926176e-02,
         1.40565550e-02,  1.26240943e-02,  5.75950406e-02,
        -2.59403400e-02,  2.35596988e-02,  3.66006754e-02,
         1.46667082e-02, -1.28894858e-02, -1.18550397e-02,
         6.84327260e-02,  7.01480210e-02, -4.00695158e-03,
         3.48143652e-02],
       [ 3.47671956e-02, -9.51403022e-01,  3.08992416e-01,
         2.52848387e-01, -1.84271708e-01,  3.63248587e-01,
        -4.48117070e-02,  2.98846722e-01, -3.70421022e-01,
        -7.62148380e-01, -5.96687291e-03,  3.83004457e-01,
         6.94596529e-01, -3.41757029e-01, -6.80524230e-01,
         1.10731579e-01],
       [-1.13979340e-01, -2.38241628e-01,  9.28341970e-02,
         1.39620110e-01, -1.79059088e-01,  1.16987109e-01,
         6.41153369e-04,  1.25571847e-01, -3.45447361e-01,
        -1.53247729e-01, -3.73975635e-02,  2.51272976e-01,
         5.32709025e-02, -2.73471922e-01, -2.73474216e-01,
        -1.26180917e-01],
       [-1.14462063e-01, -2.47986183e-01,  5.19472398e-02,
        -1.61655061e-02, -5.22358268e-02,  1.05869070e-01,
         5.47224320e-02,  3.65207233e-02, -1.53931484e-01,
        -1.64267048e-02,  5.09677120e-02, -7.84308016e-02,
         2.82941163e-01,  7.65068531e-02, -3.15730423e-01,
        -1.01133801e-01],
       [-5.38370907e-02, -9.14357156e-02, -5.58921136e-02,
        -7.36455172e-02, -5.86270913e-02, -1.19184017e-01,
        -2.22186875e-02, -1.88279837e-01,  2.85208076e-01,
         1.17755644e-01,  2.85326634e-02, -2.52908021e-01,
        -5.04844598e-02,  3.86847496e-01,  2.82812625e-01,
        -3.35963786e-01],
       [ 4.47880745e-01, -9.78966281e-02, -1.55243754e-01,
         7.11560845e-02, -6.18057922e-02, -3.13493758e-02,
        -1.69793796e-02, -1.92908034e-01,  4.86551732e-01,
         1.74678445e-01, -4.37568277e-02, -1.36614010e-01,
         2.66107414e-02,  3.37497026e-01,  2.56740928e-01,
        -1.76853836e-01],
       [ 7.19717704e-03,  4.53553945e-01, -1.73095733e-01,
        -9.42994282e-02, -8.31906032e-03,  3.73371039e-03,
        -6.38114959e-02, -1.19334109e-01,  5.97011708e-02,
         2.41643503e-01, -3.75949852e-02, -1.39436662e-01,
        -3.38276476e-01, -3.57796609e-01,  1.59819290e-01,
         1.09070681e-01],
       [-2.24129543e-01, -2.26395190e-01,  3.84776443e-01,
        -1.91149846e-01,  7.69059807e-02,  1.60006464e-01,
        -1.98481828e-02,  2.67062336e-01, -4.34279472e-01,
        -3.09531659e-01,  7.09814066e-03,  5.71585059e-01,
         3.13584149e-01, -3.72460634e-01, -4.10116136e-01,
         2.15786383e-01],
       [-1.01954877e-01, -4.99551773e-01,  1.40050098e-01,
         3.27302784e-01, -2.42462024e-01,  4.62773666e-02,
        -3.50542404e-02,  8.69732797e-02, -2.65027285e-01,
        -2.92777270e-01, -5.27573526e-02,  1.30017161e-01,
         2.38734677e-01,  4.97126020e-02, -1.77578360e-01,
        -2.03939795e-01],
       [-1.21154450e-01, -4.28973913e-01,  2.12438494e-01,
         1.39706150e-01, -1.68709800e-01,  4.49250937e-02,
        -8.09983991e-04,  1.20263740e-01, -3.48688781e-01,
        -3.25309604e-01, -5.91744483e-02,  6.98499382e-02,
         2.06707567e-01, -1.97124898e-01, -3.14756811e-01,
        -1.64890781e-01],
       [ 1.36782341e-02, -1.79883644e-01,  2.28997767e-02,
         6.43424019e-02, -5.04973866e-02,  2.46488173e-02,
         1.42910164e-02, -2.85635944e-02, -7.44352415e-02,
        -1.40644079e-02,  1.84566807e-02, -7.82130286e-02,
         5.92956357e-02, -9.44913030e-02, -1.86719105e-01,
        -2.57942844e-02],
       [ 1.01177588e-01,  4.99767661e-02,  1.22627974e-01,
         4.44451384e-02,  9.89382565e-02,  1.92785505e-02,
        -5.99090159e-02,  8.90511498e-02,  3.77936177e-02,
        -1.01029962e-01, -3.42117324e-02,  8.09109807e-02,
         1.04668908e-01, -7.31693506e-02, -1.75771378e-02,
         4.52216575e-03],
       [-1.99194506e-01, -1.50351331e-01, -2.90478151e-02,
        -8.36983845e-02, -4.41482812e-02,  3.38701643e-02,
        -1.27493711e-02, -2.83830613e-02, -1.12377487e-01,
        -8.97077024e-02,  4.84277029e-03, -4.71413769e-02,
        -4.56028525e-03,  4.88145836e-02, -9.00269896e-02,
        -8.02772790e-02],
       [-8.99817124e-02, -1.64091334e-01, -8.00468214e-03,
        -1.26235232e-01, -6.29020333e-02, -6.72698542e-02,
        -5.04876263e-02, -3.49023044e-02,  2.20111124e-02,
         1.20459404e-02, -3.07002142e-02, -2.75261216e-02,
        -5.60710058e-02,  5.13369106e-02, -8.32454041e-02,
         9.23626572e-02],
       [ 1.72568914e-02, -1.02937058e-01, -2.20883518e-01,
        -1.13318130e-01, -5.81419580e-02, -6.19196743e-02,
        -2.43756231e-02, -6.50150031e-02, -2.50460412e-02,
         1.49124429e-01,  4.32011485e-02, -5.17427437e-02,
        -5.98195866e-02,  7.71416202e-02, -3.08205876e-02,
        -5.04946597e-02],
       [-1.30655006e-01, -3.74162197e-01,  4.57914397e-02,
        -4.21384536e-02,  3.28000821e-02, -1.77370086e-01,
        -5.09043671e-02,  3.48788104e-03,  2.06616707e-02,
        -1.55132607e-01,  2.35120114e-02,  4.17811684e-02,
         1.52736604e-01, -4.13659848e-02, -1.00097187e-01,
         7.20804604e-03],
       [ 6.21403009e-02, -1.46256581e-01, -6.29504323e-02,
        -1.52101070e-01, -5.36352918e-02, -2.80308072e-02,
        -2.91346740e-02, -5.48543073e-02, -2.68510971e-02,
        -6.54924614e-03, -5.65094687e-02, -8.77962634e-03,
        -3.88033651e-02,  1.51318852e-02, -1.13780349e-01,
         2.04025321e-02],
       [-1.56409308e-01, -1.19627044e-01, -5.14307478e-03,
        -1.26988739e-01,  2.33218640e-01, -1.17881201e-01,
        -5.39907664e-02,  1.21948667e-01, -1.87665582e-01,
        -2.62252361e-01, -3.02973352e-02,  4.32836890e-01,
         2.14985553e-02, -1.99544981e-01, -2.22640753e-01,
         2.05753177e-01]], dtype=float32)

In [40]:
len(pesos0[0])

30

In [41]:
pesos1 = rede_neural.layers[1].get_weights()
pesos1

[array([[ 0.12740424, -0.01470884,  0.09540726, -0.05133106, -0.04499373,
          0.04238191, -0.15218346, -0.02992122,  0.00304636, -0.11131594,
          0.01479638,  0.11416094, -0.186449  , -0.1135746 ,  0.12175463,
         -0.20003012],
        [ 0.16172332,  0.24110672, -0.00376659, -0.01554768, -0.0039378 ,
          0.15094747,  0.104794  , -0.01127809, -0.02750965,  0.1158377 ,
         -0.00218857, -0.09856465,  0.11151388,  0.30752543, -0.07479248,
         -0.05164405],
        [-0.21058972,  0.41321233,  0.01498056, -0.01789526, -0.07223802,
         -0.04741577,  0.07994135, -0.07658455, -0.00235172,  0.20768291,
         -0.05987078,  0.01224441,  0.03844822,  0.0138152 ,  0.03203773,
         -0.05495207],
        [-0.03112442, -0.06394624,  0.02749593,  0.02862238, -0.04821473,
         -0.06363183, -0.1147263 , -0.02141481, -0.0428625 , -0.18143111,
         -0.03156371,  0.15232266, -0.1628679 , -0.19495168,  0.11308401,
         -0.06372456],
        [ 0.07748418,  0.26203993, -0.0135696 , -0.00445328, -0.04785881,
          0.11660023,  0.01909447,  0.07554214, -0.04452087,  0.18653437,
         -0.03379751, -0.06181586,  0.09009838,  0.14423738, -0.1390657 ,
          0.03678011],
        [ 0.09190262, -0.1843608 , -0.11714486,  0.01260532, -0.00825385,
         -0.11279477, -0.15193483,  0.00858482, -0.04167457, -0.1708921 ,
         -0.02260572,  0.1961749 , -0.26426354, -0.07686077,  0.13380963,
         -0.08767748],
        [ 0.01679717, -0.0373111 , -0.03016941,  0.01003323,  0.00418061,
          0.00110624, -0.05095664,  0.03120822,  0.01552814, -0.01471955,
          0.02409467,  0.02426136,  0.01245413,  0.02052862, -0.03951827,
          0.01738651],
        [-0.05179265,  0.25865573, -0.09931587, -0.04861181,  0.01377101,
          0.00894923,  0.07501268, -0.06666981, -0.03791239,  0.08896454,
         -0.05288551,  0.16742365, -0.1140238 ,  0.11381906,  0.11171547,
          0.02349152],
        [ 0.04541329,  0.2528528 ,  0.00308413, -0.03776676,  0.0020175 ,
          0.12785795,  0.04705691, -0.06682803, -0.0176969 ,  0.15819469,
         -0.04115952,  0.0175349 ,  0.08229315, -0.18976873, -0.00796436,
         -0.09846668],
        [ 0.11166136,  0.33249974, -0.12723163, -0.03703896, -0.01433628,
          0.08883575,  0.02325744,  0.03983385, -0.03063273,  0.15371352,
         -0.00589294, -0.07717526,  0.01172629,  0.07781595,  0.01517204,
         -0.03682738],
        [-0.07149485,  0.003438  , -0.04450583, -0.05133339,  0.00788298,
         -0.01672336,  0.01741271,  0.01825332,  0.01418913,  0.01663265,
          0.00410132,  0.03712852, -0.02024414, -0.0541199 , -0.04673632,
          0.08674349],
        [-0.45536327,  0.1152369 ,  0.298795  , -0.04229752, -0.01408984,
         -0.35976988, -0.4379174 ,  0.06365774,  0.00582685,  0.3583695 ,
         -0.02851545, -0.25696874, -0.40219942, -0.64950854, -0.22565798,
          0.17200261],
        [-0.11187828,  0.32376048, -0.08517885, -0.01310461,  0.01446828,
         -0.14865604, -0.00948759,  0.03925585, -0.02498622,  0.06065974,
         -0.01320193,  0.08874494, -0.03953483, -0.05695523,  0.07844125,
         -0.00202694],
        [-0.02533229,  0.2949995 ,  0.00258809,  0.02174004, -0.03801664,
          0.1273656 ,  0.01366099, -0.00835134, -0.00711168,  0.13210411,
          0.01462476,  0.01539755,  0.00468064, -0.12348192, -0.04891432,
          0.02102408],
        [ 0.00879686,  0.31625798,  0.07563805,  0.01482317, -0.01961102,
          0.14616229,  0.09403641,  0.01314807,  0.01495266,  0.1493348 ,
         -0.04265354, -0.05736029,  0.0668665 , -0.12396556,  0.01781257,
          0.01711859],
        [ 0.09092549,  0.18100604, -0.00430769, -0.00525187, -0.04146389,
          0.03852688,  0.02004996, -0.06234358,  0.00342127,  0.05869724,
          0.04433446,  0.12691838, -0.03849048,  0.15428281,  0.10494495,
          0.01195909]], dtype=float32),
 array([ 0.07345947, -0.31728956,  0.05569681, -0.00915072, -0.008287  ,
         0.20889883,  0.1506521 , -0.13822219, -0.01885655, -0.32399496,
         0.0243653 ,  0.15125255,  0.14852044,  0.1064979 ,  0.23184124,
        -0.17294048], dtype=float32)]

In [42]:
pesos2 = rede_neural.layers[2].get_weights()
pesos2

[array([[ 0.2550511 ],
        [-0.08174229],
        [-0.35325742],
        [-0.30163267],
        [-0.47854567],
        [ 0.4171982 ],
        [ 0.2287405 ],
        [-0.45437086],
        [-0.04507682],
        [-0.19553757],
        [ 0.006693  ],
        [ 0.27920365],
        [ 0.13607843],
        [ 0.27419013],
        [ 0.20190437],
        [-0.31170568]], dtype=float32),
 array([0.2678655], dtype=float32)]

In [18]:
previsoes = rede_neural.predict(X_teste)
previsoes = previsoes > 0.5

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [19]:
previsoes

array([[False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True]])

In [20]:
y_teste

     0
129  0
293  1
294  1
295  1
173  1
..  ..
261  0
203  0
478  1
331  1
306  1

[143 rows x 1 columns]

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [22]:
accuracy_score(y_teste, previsoes)

0.8391608391608392

In [23]:
confusion_matrix(y_teste, previsoes)

array([[25, 21],
       [ 2, 95]])

In [25]:
25 + 95, 21 + 2

(120, 23)

In [26]:
128 / 143, 23 / 143

(0.8951048951048951, 0.16083916083916083)

In [33]:
rede_neural.evaluate(X_teste, y_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7832 - loss: 2.3575

[2.3574955463409424, 0.7832167744636536]